services:
  - type: web
    name: symfony-app
    env: php
    buildCommand: "composer install && yarn install && yarn encore production"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
