services:
  - type: web
    name: sf_tamizee
    env: docker
    buildCommand: |
      docker build -t sf_tamizee .
    startCommand: docker run -p 10000:80 sf_tamizee
    envVars:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/sf_buy_buy_buy
