services:
  - type: web
    name: sf-tamizee
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true

envVars:
  - key: APP_ENV
    value: prod
  - key: APP_DEBUG
    value: 0

